'use client';
import Link from 'next/link';import { Area,AreaChart,Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';import { Activity,BarChart3,Bell,ChevronRight,Home,Lightbulb,Settings,Sliders,Sun,Wind,Zap } from 'lucide-react';
import { currentReading, hourly } from '@/lib/mock-data';import { gbp,totalFinancialBenefit } from '@/lib/calculations';
export const nav=[['/dashboard','Now',Home],['/history','History',BarChart3],['/insights','Insights',Lightbulb],['/system','System',Activity],['/settings','Settings',Settings]] as const;
export function Logo(){return <Link href="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-2xl bg-cyan-300/15 text-cyan-200 ring-1 ring-cyan-200/30"><Zap size={19}/></span><span>my electricity</span></Link>}
export function AppShell({children}:{children:React.ReactNode}){return <div className="min-h-screen pb-24 md:pb-0"><aside className="fixed left-0 top-0 z-20 hidden h-full w-64 border-r border-white/10 bg-[#07111F]/75 p-6 backdrop-blur-xl md:block"><Logo/><nav className="mt-10 space-y-2">{nav.map(([href,label,Icon])=><Link key={href} href={href} className="flex items-center gap-3 rounded-2xl px-4 py-3 text-slate-300 hover:bg-white/10 hover:text-white"><Icon size={18}/>{label}</Link>)}</nav><p className="absolute bottom-6 text-sm text-slate-500">myelectricity.co.uk</p></aside><main className="md:ml-64">{children}</main><nav className="fixed bottom-3 left-3 right-3 z-30 flex justify-around rounded-3xl border border-white/10 bg-[#0D1B2E]/90 p-2 backdrop-blur-xl md:hidden">{nav.map(([href,label,Icon])=><Link key={href} href={href} className="flex flex-col items-center gap-1 rounded-2xl px-3 py-2 text-xs text-slate-300"><Icon size={18}/>{label}</Link>)}</nav></div>}
export function StatusPill({children,tone='live'}:{children:React.ReactNode;tone?:'live'|'warn'|'muted'}){return <span className={`rounded-full px-3 py-1 text-xs font-medium ring-1 ${tone==='live'?'bg-cyan-300/10 text-cyan-100 ring-cyan-200/30':tone==='warn'?'bg-amber-300/10 text-amber-100 ring-amber-200/30':'bg-white/10 text-slate-200 ring-white/15'}`}>{children}</span>}
export function SourceBadge({type}:{type:'Solar'|'Wind'|'Hybrid'}){const Icon=type==='Wind'?Wind:Sun;return <span className="inline-flex items-center gap-1 rounded-full bg-white/10 px-3 py-1 text-xs text-slate-100 ring-1 ring-white/10"><Icon size={14}/>{type}</span>}
export function MetricCard({label,value,sub,accent='cyan'}:{label:string;value:string;sub:string;accent?:'cyan'|'lime'|'amber'}){return <div className="glass rounded-3xl p-5"><p className="text-sm text-slate-400">{label}</p><p className={`mt-2 text-3xl font-semibold ${accent==='lime'?'text-lime-200':accent==='amber'?'text-amber-200':'text-cyan-100'}`}>{value}</p><p className="mt-2 text-sm text-slate-400">{sub}</p></div>}
export function EnergyOrb(){return <div className="relative mx-auto grid h-72 w-72 place-items-center overflow-hidden rounded-full md:h-96 md:w-96"><div className="flow"/><div className="orb relative grid h-56 w-56 place-items-center rounded-full text-center md:h-72 md:w-72"><div><p className="text-sm uppercase tracking-[.25em] text-cyan-950/80">Generating now</p><p className="text-5xl font-bold text-white">{currentReading.currentPowerKw} kW</p><p className="mt-3 max-w-44 text-sm text-cyan-50">Enough to cover most daytime household use.</p></div></div></div>}
export function GenerationChart({data=hourly,type='area'}:{data?:any[];type?:'area'|'bar'}){return <div className="h-72 w-full"> <ResponsiveContainer>{type==='area'?<AreaChart data={data}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#39E6FF" stopOpacity={.55}/><stop offset="95%" stopColor="#39E6FF" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.08)"/><XAxis dataKey="time" stroke="#94A3B8"/><YAxis stroke="#94A3B8"/><Tooltip contentStyle={{background:'#0D1B2E',border:'1px solid rgba(255,255,255,.12)',borderRadius:16}}/><Area type="monotone" dataKey="value" stroke="#39E6FF" fill="url(#g)" strokeWidth={3}/><Area type="monotone" dataKey="wind" stroke="#B8FF5C" fill="transparent" strokeWidth={2}/></AreaChart>:<BarChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)"/><XAxis dataKey="date" stroke="#94A3B8"/><YAxis stroke="#94A3B8"/><Tooltip contentStyle={{background:'#0D1B2E',border:'1px solid rgba(255,255,255,.12)',borderRadius:16}}/><Bar dataKey="generation" fill="#39E6FF" radius={[8,8,0,0]}/></BarChart>}</ResponsiveContainer></div>}
export function PageHeader({title,sub}:{title:string;sub:string}){return <header className="flex flex-wrap items-center justify-between gap-4 px-5 py-6 md:px-10"><div><Logo/><h1 className="mt-8 text-4xl font-semibold md:text-6xl">{title}</h1><p className="mt-3 max-w-2xl text-slate-400">{sub}</p></div><div className="flex gap-2"><StatusPill>Live</StatusPill><StatusPill tone="muted">Home</StatusPill></div></header>}
export function CTA({href,children}:{href:string;children:React.ReactNode}){return <Link href={href} className="inline-flex items-center gap-2 rounded-full bg-cyan-300 px-5 py-3 font-semibold text-slate-950 shadow-[0_0_30px_rgba(57,230,255,.35)]">{children}<ChevronRight size={18}/></Link>}
export function Story(){const benefit=totalFinancialBenefit(5.6,3.1,{currency:'GBP',importPricePerKwh:.28,exportPricePerKwh:.15});return <div className="glass rounded-3xl p-6"><div className="mb-3 flex items-center gap-2 text-cyan-100"><Bell size={18}/>Energy story</div><p className="text-xl">Today your system generated <b>8.7 kWh</b>, worth about <b>{gbp(benefit)}</b>, with your strongest output around <b>13:20</b>.</p><p className="mt-3 text-sm text-slate-400">Estimated from your tariff · Based on mock/demo data</p></div>}
export function ToggleRow({items}:{items:string[]}){return <div className="flex gap-2 overflow-auto no-scrollbar">{items.map((i,n)=><button key={i} className={`rounded-full px-4 py-2 text-sm ${n===0?'bg-white text-slate-950':'bg-white/10 text-slate-200'}`}>{i}</button>)}</div>}
