import { Device, EnergyReading, Insight, Site, Tariff } from './types';
export const site:Site={id:'home',userId:'demo',name:'Home',postcode:'BS1',source:'hybrid',installedCapacityKw:5.8};
export const tariff:Tariff={currency:'GBP',importPricePerKwh:.28,exportPricePerKwh:.15,standingChargePerDay:.53};
const now = new Date('2026-06-29T13:20:00Z');
export const currentReading:EnergyReading={timestamp:now.toISOString(),currentPowerKw:2.4,energyTodayKwh:8.7,energyLifetimeKwh:12842,sourceBreakdown:{solarKw:1.8,windKw:.6},importedKwh:1.9,exportedKwh:3.1,batterySoc:68,inverterStatus:'normal',connectionStatus:'online'};
export const hourly = Array.from({length:24},(_,h)=>({time:`${String(h).padStart(2,'0')}:00`,solar:+(Math.max(0,Math.sin((h-6)/12*Math.PI))*3.2*(.85+((h%3)*.08))).toFixed(2),wind:+((.25+Math.sin(h*.9+1)*.22+((h%5)*.07))).toFixed(2),value:0})).map(r=>({...r,value:+(r.solar+r.wind).toFixed(2),money:+((r.solar+r.wind)*.28).toFixed(2)}));
export const history = Array.from({length:30},(_,i)=>{const v=+(12+Math.sin(i/3)*6+(i%7)*.8).toFixed(1);return {date:`${i+1} Jun`,generation:v,savings:+(v*.24).toFixed(2),exported:+(v*.34).toFixed(1)}});
export const devices:Device[]=[{id:'inv',siteId:'home',name:'Inverter',type:'inverter',status:'online',lastSeen:new Date(Date.now()-4*60000).toISOString(),firmware:'Demo 1.8.2',connectionType:'cloud_api',plainStatus:'Your inverter is online.'},{id:'solar',siteId:'home',name:'Solar array',type:'solar_array',status:'online',lastSeen:new Date(Date.now()-5*60000).toISOString(),connectionType:'local_network',plainStatus:'Solar generation is reporting normally.'},{id:'wind',siteId:'home',name:'Wind turbine',type:'wind_turbine',status:'online',lastSeen:new Date(Date.now()-6*60000).toISOString(),connectionType:'modbus',plainStatus:'Wind readings are coming through.'},{id:'bat',siteId:'home',name:'Battery',type:'battery',status:'online',lastSeen:new Date(Date.now()-8*60000).toISOString(),firmware:'Placeholder',connectionType:'local_network',plainStatus:'Battery state is available.'}];
export const insights:Insight[]=[{id:'peak',title:'Your system usually peaks between 12:00 and 14:00.',body:'Today follows the same pattern, with strongest output around 13:20.',tone:'good',confidence:'Based on mock/demo data'},{id:'pace',title:'Today is 11% below your 30-day average.',body:'Cloudier midday hours are the likely reason. No action needed unless the gap grows.',tone:'neutral',confidence:'Estimated from recent readings'},{id:'wind',title:'Wind generation was strongest overnight.',body:'The turbine added steady background power while solar was quiet.',tone:'good',confidence:'Based on source split'},{id:'fridge',title:'This month could run a fridge for roughly 14 months.',body:'A simple way to picture the energy your home has made.',tone:'good',confidence:'Estimated from your tariff'}];
